import Template_1 from "./templates/template_1";
import Template_2 from "./templates/template_2";
import Template_3 from "./templates/template_3";
import Template_4 from "./templates/template_4";
import Template_5 from "./templates/template_5";
import Template_6 from "./templates/template_6";
import Template_7 from "./templates/template_7";
import Template_8 from "./templates/template_8";
import Template_9 from "./templates/template_9";
import Template_10 from "./templates/template_10";
import Template_11 from "./templates/template_11";
import Template_12 from "./templates/template_12";
import Template_13 from "./templates/template_13";
import Template_14 from "./templates/template_14";
import Template_15 from "./templates/template_15";
import Template_16 from "./templates/template_16";
import Template_17 from "./templates/template_17";
import Template_18 from "./templates/template_18";
import Template_19 from "./templates/template_19";
import Template_20 from "./templates/template_20";
import Template_21 from "./templates/template_21";
import Template_22 from "./templates/template_22";
import Template_23 from "./templates/template_23";
import Template_24 from "./templates/template_24";
import Template_25 from "./templates/template_25";
import Template_26 from "./templates/template_26";
import Template_27 from "./templates/template_27";
import Template_28 from "./templates/template_28";
import Template_29 from "./templates/template_29";
import Template_30 from "./templates/template_30";
import Template_31 from "./templates/template_31";
import Template_32 from "./templates/template_32";
import Template_33 from "./templates/template_33";
import Template_34 from "./templates/template_34";
import Template_35 from "./templates/template_35";
import Template_36 from "./templates/template_36";

export const templateArray = [
  {
    id: "1",
    set: "1",
    title: "Template 1",
    template: <Template_1 />,
    size: {
      small: "w-[382px] h-[346px]",
      medium: "w-[462px] h-[426px]",
      large: "w-[482px] h-[482px]",
    },
    contents: {
      h1: "Security Code",
      h2: "This code expires in 24 hours",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "Code",
      buttonCancel: "Cancel",
      buttonApply: "Continue",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: true,
      image: false,
    },
  },
  {
    id: "2",
    set: "1",
    title: "Template 2",
    template: <Template_2 />,
    size: {
      small: "w-[352px] h-[470px]",
      medium: "w-[440px] h-[550px]",
      large: "w-[500px] h-[600px]",
    },
    contents: {
      h1: "Install local now",
      h2: "We’ve gone native, try it!",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "Not now",
      buttonApply: "Continue",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: false,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: true,
    },
  },
  {
    id: "3",
    set: "1",
    title: "Template 3",
    template: <Template_3 />,
    size: {
      small: "w-[342px] h-[470px]",
      medium: "w-[480px] h-[516px]",
      large: "w-[520px] h-[590px]",
    },
    contents: {
      h1: "Delete your profile",
      h2: "Your profile will be automatically deleted after 1 month",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "You won’t be able to access to your profile after 30.08.2021.",
      buttonCancel: "Delete my profile",
      buttonApply: "Cancel",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: true,
      image: false,
    },
  },
  {
    id: "4",
    set: "1",
    title: "Template 4",
    template: <Template_4 />,
    size: {
      small: "w-[382px] h-[346px]",
      medium: "w-[462px] h-[426px]",
      large: "w-[482px] h-[482px]",
    },
    contents: {
      h1: "Join our mail list",
      h2: "Save up to 30% of your next order",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "Enter your email",
      buttonCancel: "Later",
      buttonApply: "Join now",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: true,
      image: false,
    },
  },
  {
    id: "5",
    set: "1",
    title: "Template 5",
    template: <Template_5 />,
    size: {
      small: "w-[410px] h-[253px]",
      medium: "w-[480px] h-[283px]",
      large: "w-[500px] h-[320px]",
    },
    contents: {
      h1: "The file is on it's way",
      h2: "You’ll get an notified when the receiver has opened the email.",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "Go to dashboard",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: false,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "6",
    set: "1",
    title: "Template 6",
    template: <Template_6 />,
    size: {
      small: "w-[430px] h-[440px]",
      medium: "w-[480px] h-[549px]",
      large: "w-[500px] h-[620px]",
    },
    contents: {
      h1: "Starter",
      h2: "1 free (then $15 per meember / month)",
      h3: "Pro",
      h4: "$19 per member/month",
      h5: "Business",
      h6: "$29 per member/month",
      p: "",
      buttonCancel: "Cancel",
      buttonApply: "Continue",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
      h6: true,
      p: false,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "7",
    set: "1",
    title: "Template 7",
    template: <Template_7 />,
    size: {
      small: "w-[350px] h-[223px]",
      medium: "w-[440px] h-[263px]",
      large: "w-[500px] h-[320px]",
    },
    contents: {
      h1: "Hi, stranger",
      h2: "Sign up now, and get a 30% discount",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "Sign up now",
      buttonApply: "Log in",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: false,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "8",
    set: "1",
    title: "Template 8",
    template: <Template_8 />,
    size: {
      small: "w-[500px] h-[360px]",
      medium: "w-[640px] h-[400px]",
      large: "w-[740px] h-[440px]",
    },
    contents: {
      h1: "Subscribe to our newsletter",
      h2: "Receive the flash news in your inbox.",
      h3: "Enter your email",
      h4: "By subscribe this form I agree to Privacy Policy.",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "Sign up now",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
      h6: false,
      p: true,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "9",
    set: "1",
    title: "Template 9",
    template: <Template_9 />,
    size: {
      small: "w-[420px] h-[650px]",
      medium: "w-[480px] h-[722px]",
      large: "w-[520px] h-[760px]",
    },
    contents: {
      h1: "Hello stranger",
      h2: "Sign up now and get 30% discount",
      h3: "Enter Full name",
      h4: "Enter your email",
      h5: "Already have an account?",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "Sign up",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
      h6: false,
      p: false,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: true,
    },
  },
  {
    id: "10",
    set: "1",
    title: "Template 10",
    template: <Template_10 />,
    size: {
      small: "w-[640px] h-[370px]",
      medium: "w-[710px] h-[418px]",
      large: "w-[750px] h-[440px]",
    },
    contents: {
      h1: "Sign up",
      h2: "Join new adventure",
      h3: "Enter Full name",
      h4: "Enter your email",
      h5: "Forgot password",
      h6: "Log In",
      p: "",
      buttonCancel: "",
      buttonApply: "Sign up",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
      h6: true,
      p: false,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: true,
    },
  },
  {
    id: "11",
    set: "1",
    title: "Template 11",
    template: <Template_11 />,
    size: {
      small: "w-[390px] h-[550px]",
      medium: "w-[460px] h-[584px]",
      large: "w-[500px] h-[600px]",
    },
    contents: {
      h1: "Check your email",
      h2: "Once you deletet your account, you’ll lose all data.",
      h3: "Enter your email",
      h4: "Already have an account?",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "Sign up",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: true,
      image: false,
    },
  },
  {
    id: "12",
    set: "1",
    title: "Template 12",
    template: <Template_12 />,
    size: {
      small: "w-[460px] h-[530px]",
      medium: "w-[480px] h-[540px]",
      large: "w-[550px] h-[563px]",
    },
    contents: {
      h1: "Sign up",
      h2: "Join new adventure",
      h3: "Enter Full name",
      h4: "Enter your email",
      h5: "Forgot password",
      h6: "Log In",
      p: "",
      buttonCancel: "",
      buttonApply: "Sign up",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
      h6: true,
      p: false,
      buttonCancel: false,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: true,
    },
  },
  {
    id: "13",
    set: "2",
    title: "Template 13",
    template: <Template_13 />,
    size: {
      small: "w-[400px] h-[380px]",
      medium: "w-[480px] h-[466px]",
      large: "w-[540px] h-[520px]",
    },
    contents: {
      h1: "Welcome to talk",
      h2: "Send friends photos, videos,locations, songs, voice messages, and more.",
      h3: "Let’s get started",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: true,
      h4: false,
      h5: false,
      h6: false,
      p: false,
      buttonCancel: false,
      buttonApply: false,
    },
    logoImage: {
      logo: true,
      image: false,
    },
  },
  {
    id: "14",
    set: "2",
    title: "Template 14",
    // template: <Template14 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "15",
    set: "2",
    title: "Template 15",
    // template: <Template15 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "16",
    set: "2",
    title: "Template 16",
    // template: <Template16 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "17",
    set: "2",
    title: "Template 17",
    // template: <Template17 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "18",
    set: "2",
    title: "Template 18",
    // template: <Template18 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "19",
    set: "2",
    title: "Template 19",
    // template: <Template19 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "20",
    set: "2",
    title: "Template 20",
    // template: <Template20 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: "21",
    set: "2",
    title: "Template 21",
    // template: <Template21 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 22,
    set: "2",
    title: "Template 22",
    // template: <Template22 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 23,
    set: "2",
    title: "Template 23",
    // template: <Template23 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 24,
    set: "2",
    title: "Template 24",
    // template: <Template24 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 25,
    set: "3",
    title: "Template 25",
    // template: <Template25 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 26,
    set: "3",
    title: "Template 26",
    // template: <Template26 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 27,
    set: "3",
    title: "Template 27",
    // template: <Template27 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 28,
    set: "3",
    title: "Template 28",
    // template: <Template28 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 29,
    set: "3",
    title: "Template 29",
    // template: <Template29 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 30,
    set: "3",
    title: "Template 30",
    // template: <Template30 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 31,
    set: "3",
    title: "Template 31",
    // template: <Template31 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 32,
    set: "3",
    title: "Template 32",
    // template: <Template32 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 33,
    set: "3",
    title: "Template 33",
    // template: <Template33 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 34,
    set: "3",
    title: "Template 34",
    // template: <Template34 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 35,
    set: "3",
    title: "Template 35",
    // template: <Template35 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
  {
    id: 36,
    set: "3",
    title: "Template 36",
    // template: <Template36 />,
    contents: {
      h1: "",
      h2: "",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "",
      buttonCancel: "",
      buttonApply: "",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },
    logoImage: {
      logo: false,
      image: false,
    },
  },
];

export const browserLanguages: any = [
  { id: "1", language: "English", code: "en", isSelected: false },
  { id: "2", language: "French", code: "fr", isSelected: false },
  { id: "3", language: "German", code: "de", isSelected: false },
  { id: "4", language: "Polish", code: "pl", isSelected: false },
  { id: "5", language: "Dutch", code: "nl", isSelected: false },
  { id: "6", language: "Finnish", code: "fi", isSelected: false },
  { id: "7", language: "Turkish", code: "tr", isSelected: false },
  { id: "8", language: "Russian", code: "ru", isSelected: false },
  { id: "9", language: "Korean", code: "ko", isSelected: false },
  { id: "10", language: "Tatar", code: "tt", isSelected: false },
  { id: "11", language: "Spanish", code: "es", isSelected: false },
  { id: "12", language: "Somali", code: "so", isSelected: false },
];
