import Template1 from "./template1";
import Template2 from "./template2";
// import Template3 from "./template3";

export const modalArray = [
  {
    "id": 1,
    "Set": "1",
    "title": "Template 1",
    "template": <Template1 />,
  },
  {
    "id": 2,
    "Set": "1",
    "title": "Template 2",
    "template": <Template2 />,
  },
  // {
  //   id: 3,
  //   Set: "1",
  //   title: "Template 3",
  //   // template: <Template3 />,
  // },
  // {
  //   id: 4,
  //   Set: "1",
  //   title: "Template 4",
  //   // template: <Template4 />,
  // },
  // {
  //   id: 5,
  //   Set: "1",
  //   title: "Template 5",
  //   // template: <Template5 />,
  // },
  // {
  //   id: 6,
  //   Set: "1",
  //   title: "Template 6",
  //   // template: <Template6 />,
  // },
  // {
  //   id: 7,
  //   Set: "1",
  //   title: "Template 7",
  //   // template: <Template7 />,
  // },
  // {
  //   id: 8,
  //   Set: "1",
  //   title: "Template 8",
  //   // template: <Template8 />,
  // },
  // {
  //   id: 9,
  //   Set: "1",
  //   title: "Template 9",
  //   // template: <Template9 />,
  // },
  // {
  //   id: 10,
  //   Set: "1",
  //   title: "Template 10",
  //   // template: <Template10 />,
  // },
  // {
  //   id: 11,
  //   Set: "1",
  //   title: "Template 11",
  //   // template: <Template11 />,
  // },
  // {
  //   id: 12,
  //   Set: "1",
  //   title: "Template 12",
  //   // template: <Template12 />,
  // },
  // {
  //   id: 13,
  //   Set: "2",
  //   title: "Template 13",
  //   // template: <Template13 />,
  // },
  // {
  //   id: 14,
  //   Set: "2",
  //   title: "Template 14",
  //   // template: <Template14 />,
  // },
  // {
  //   id: 15,
  //   Set: "2",
  //   title: "Template 15",
  //   // template: <Template15 />,
  // },
  // {
  //   id: 16,
  //   Set: "2",
  //   title: "Template 16",
  //   // template: <Template16 />,
  // },
  // {
  //   id: 17,
  //   Set: "2",
  //   title: "Template 17",
  //   // template: <Template17 />,
  // },
  // {
  //   id: 18,
  //   Set: "2",
  //   title: "Template 18",
  //   // template: <Template18 />,
  // },
  // {
  //   id: 19,
  //   Set: "2",
  //   title: "Template 19",
  //   // template: <Template19 />,
  // },
  // {
  //   id: 20,
  //   Set: "2",
  //   title: "Template 20",
  //   // template: <Template20 />,
  // },
  // {
  //   id: 21,
  //   Set: "2",
  //   title: "Template 21",
  //   // template: <Template21 />,
  // },
  // {
  //   id: 22,
  //   Set: "2",
  //   title: "Template 22",
  //   // template: <Template22 />,
  // },
  // {
  //   id: 23,
  //   Set: "2",
  //   title: "Template 23",
  //   // template: <Template23 />,
  // },
  // {
  //   id: 24,
  //   Set: "2",
  //   title: "Template 24",
  //   // template: <Template24 />,
  // },
  // {
  //   id: 25,
  //   Set: "3",
  //   title: "Template 25",
  //   // template: <Template25 />,
  // },
  // {
  //   id: 26,
  //   Set: "3",
  //   title: "Template 26",
  //   // template: <Template26 />,
  // },
  // {
  //   id: 27,
  //   Set: "3",
  //   title: "Template 27",
  //   // template: <Template27 />,
  // },
  // {
  //   id: 28,
  //   Set: "3",
  //   title: "Template 28",
  //   // template: <Template28 />,
  // },
  // {
  //   id: 29,
  //   Set: "3",
  //   title: "Template 29",
  //   // template: <Template29 />,
  // },
  // {
  //   id: 30,
  //   Set: "3",
  //   title: "Template 30",
  //   // template: <Template30 />,
  // },
  // {
  //   id: 31,
  //   Set: "3",
  //   title: "Template 31",
  //   // template: <Template31 />,
  // },
  // {
  //   id: 32,
  //   Set: "3",
  //   title: "Template 32",
  //   // template: <Template32 />,
  // },
  // {
  //   id: 33,
  //   Set: "3",
  //   title: "Template 33",
  //   // template: <Template33 />,
  // },
  // {
  //   id: 34,
  //   Set: "3",
  //   title: "Template 34",
  //   // template: <Template34 />,
  // },
  // {
  //   id: 35,
  //   Set: "3",
  //   title: "Template 35",
  //   // template: <Template35 />,
  // },
  // {
  //   id: 36,
  //   Set: "3",
  //   title: "Template 36",
  //   // template: <Template36 />,
  // },
];
