import Template_1 from "./template_1";
import Template_2 from "./template_2";

export const templateArray = [
  {
    id: "1",
    set: "1",
    title: "Template 1",
    template: <Template_1 />,
    contents: {
      h1: "Security Code",
      h2: "This code expires in 24 hours",
      h3: "",
      h4: "",
      h5: "",
      h6: "",
      p: "Code",
      buttonCancel: "Cancel",
      buttonApply: "Continue",
    },
    trfl: {
      h1: true,
      h2: true,
      h3: false,
      h4: false,
      h5: false,
      h6: false,
      p: true,
      buttonCancel: true,
      buttonApply: true,
    },

    logoImage: {
      logo: true,
      image: false,
    },
  },
  // {
  //   id: "2",
  //   set: "1",
  //   title: "Template 2",
  //   template: <Template_2 />,
  //   contents: {
  //     h1: "Security Code",
  //     h2: "This code expires in 24 hours",
  //     p: "Code",
  //     buttonCancel: "Cancel",
  //     buttonApply: "Continue",
  //   },
  // },
  //   id: "3",
  //   set: "1",
  //   title: "Template 3",
  //   // template: <Template3 />,
  // },
  // {
  //   id: "4",
  //   set: "1",
  //   title: "Template 4",
  //   // template: <Template4 />,
  // },
  // {
  //   id: "5",
  //   set: "1",
  //   title: "Template 5",
  //   // template: <Template5 />,
  // },
  // {
  //   id: "6",
  //   set: "1",
  //   title: "Template 6",
  //   // template: <Template6 />,
  // },
  // {
  //   id: "7",
  //   set: "1",
  //   title: "Template 7",
  //   // template: <Template7 />,
  // },
  // {
  //   id: "8",
  //   set: "1",
  //   title: "Template 8",
  //   // template: <Template8 />,
  // },
  // {
  //   id: "9",
  //   set: "1",
  //   title: "Template 9",
  //   // template: <Template9 />,
  // },
  // {
  //   id: "10",
  //   set: "1",
  //   title: "Template 10",
  //   // template: <Template10 />,
  // },
  // {
  //   id: "11",
  //   set: "1",
  //   title: "Template 11",
  //   // template: <Template11 />,
  // },
  // {
  //   id: "12",
  //   set: "1",
  //   title: "Template 12",
  //   // template: <Template12 />,
  // },
  // {
  //   id: "13",
  //   set: "2",
  //   title: "Template 13",
  //   // template: <Template13 />,
  // },
  // {
  //   id: "14",
  //   set: "2",
  //   title: "Template 14",
  //   // template: <Template14 />,
  // },
  // {
  //   id: "15",
  //   set: "2",
  //   title: "Template 15",
  //   // template: <Template15 />,
  // },
  // {
  //   id: "16",
  //   set: "2",
  //   title: "Template 16",
  //   // template: <Template16 />,
  // },
  // {
  //   id: "17",
  //   set: "2",
  //   title: "Template 17",
  //   // template: <Template17 />,
  // },
  // {
  //   id: "18",
  //   set: "2",
  //   title: "Template 18",
  //   // template: <Template18 />,
  // },
  // {
  //   id: "19",
  //   set: "2",
  //   title: "Template 19",
  //   // template: <Template19 />,
  // },
  // {
  //   id: "20",
  //   set: "2",
  //   title: "Template 20",
  //   // template: <Template20 />,
  // },
  // {
  //   id: "21",
  //   set: "2",
  //   title: "Template 21",
  //   // template: <Template21 />,
  // },
  // {
  //   id: 22,
  //   set: "2",
  //   title: "Template 22",
  //   // template: <Template22 />,
  // },
  // {
  //   id: 23,
  //   set: "2",
  //   title: "Template 23",
  //   // template: <Template23 />,
  // },
  // {
  //   id: 24,
  //   set: "2",
  //   title: "Template 24",
  //   // template: <Template24 />,
  // },
  // {
  //   id: 25,
  //   set: "3",
  //   title: "Template 25",
  //   // template: <Template25 />,
  // },
  // {
  //   id: 26,
  //   set: "3",
  //   title: "Template 26",
  //   // template: <Template26 />,
  // },
  // {
  //   id: 27,
  //   set: "3",
  //   title: "Template 27",
  //   // template: <Template27 />,
  // },
  // {
  //   id: 28,
  //   set: "3",
  //   title: "Template 28",
  //   // template: <Template28 />,
  // },
  // {
  //   id: 29,
  //   set: "3",
  //   title: "Template 29",
  //   // template: <Template29 />,
  // },
  // {
  //   id: 30,
  //   set: "3",
  //   title: "Template 30",
  //   // template: <Template30 />,
  // },
  // {
  //   id: 31,
  //   set: "3",
  //   title: "Template 31",
  //   // template: <Template31 />,
  // },
  // {
  //   id: 32,
  //   set: "3",
  //   title: "Template 32",
  //   // template: <Template32 />,
  // },
  // {
  //   id: 33,
  //   set: "3",
  //   title: "Template 33",
  //   // template: <Template33 />,
  // },
  // {
  //   id: 34,
  //   set: "3",
  //   title: "Template 34",
  //   // template: <Template34 />,
  // },
  // {
  //   id: 35,
  //   set: "3",
  //   title: "Template 35",
  //   // template: <Template35 />,
  // },
  // {
  //   id: 36,
  //   set: "3",
  //   title: "Template 36",
  //   // template: <Template36 />,
  // },
];
